### ISSUE TITLE
Module not found: Can't resolve '@fontwesome/react-fontawesome'

### ISSUE THREAD

**Issue by ryuujo** [FortAwesome/react-fontawesome#236]
I got an error while importing FontAwesome.
Here's the error:

> ./src/routes/Home/Home.jsx
> Module not found: Can't resolve '@fontwesome/react-fontawesome' in 'C:\selfProject\faq-page\src\routes\Home'

This is my code (I just only importing it):
```
import React, { Component } from "react";
import { FontAwesomeIcon } from "@fontwesome/react-fontawesome";
import { faSearch } from "@fortawesome/free-solid-svg-icons";

import "./Home.css";

class Home extends Component {
  render() {
    return (
      <div className="home">
        <div className="container container-title">
...
```

I already tried to remove `node_modules` and `yarn.lock` and tried to re-install it again, but still have the same issue.

**Comment by Namchee** [comment]
I think the import path is wrong. Shouldn't it be `@fortawesome/<write module here>` and not `@fontwesome/<write module here>`?  

Refer to: 
https://github.com/FortAwesome/react-fontawesome#installation

**Comment by ryandrew14** [comment]
@Namchee is right, this is the problem.

**Comment by mirukusheki** [comment]
Thanks @Namchee the problem has been solved! ^^

**Comment by Igor2122** [comment]
there is this typo in https://www.npmjs.com/package/@fortawesome/react-fontawesome

import ReactDOM from 'react-dom'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCoffee } from '@fortawesome/free-solid-svg-icons'
 
const element = <FontAwesomeIcon icon={faCoffee} />
 
ReactDOM.render(element, document.body)

**Comment by hridoyraisul** [comment]
> Thanks @Namchee the problem has been solved! ^^

please tell me how it solved? I have the same problem.

**Comment by robmadole** [comment]
@hridoyraisul check the package namespace `@fortawesome` not `@fontawesome` "R" versus "N"

**Comment by hridoyraisul** [comment]
> @hridoyraisul check the package namespace `@fortawesome` not `@fontawesome` "R" versus "N"

Thanks a lot ,, I fixed it

**Comment by amastaneh** [comment]
It's part of the NPM installation guideline in https://www.npmjs.com/package/@fortawesome/free-solid-svg-icons 

![image](https://user-images.githubusercontent.com/6195199/104972450-c7c2f380-59bf-11eb-8be2-0f4bc1053786.png)

**Comment by Afsana1313** [comment]
I have faced the same issue. Even I used the folder name correctly as '@fortawesome', still, there is an error showing as 'Module not found: Can't resolve'

**Comment by robmadole** [comment]
@Afsana1313 paste the error please and I'll take a look. I need to see if exactly.

**Comment by hasansiam45** [comment]
still not solved.
this is my importing code:
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

**Comment by robmadole** [comment]
@Afsana1313 @hasansiam45 please provide a reproducible example (something we can run `npm install` on) and we'll take a look.

**Comment by robmadole** [comment]
@NsdHSO you'll have to give us some additional details. If it doesn't match this issue ("Module not found: Can't resolve '@fontwesome/react-fontawesome'") then please open a new issue in this project.

**Comment by NsdHSO** [comment]
@robmadole  I configured it out, I had to give it an npm i. Tanks anyway.

**Comment by srikanthch1919** [comment]
I have faced the same issue. Even I used the folder name correctly as import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
this is the error:Module not found: Can't resolve '@fortawesome/react-fontawesome' in 'E:\react-music\src\components'

**Comment by sergio-ivanuzzo** [comment]
Faced with similar issue, for me helped to install @fortawesome/fontawesome-svg-core

**Comment by NsdHSO** [comment]
Thanks i resolved this problem
YOU have a good day. 


Trimis din Yahoo Mail pentru iPhone


La miercuri, iunie 9, 2021, 10:57 p.m., Sergio ***@***.***> a scris:




Faced with similar issue, for me helped to install @fortawesome/fontawesome-svg-core

**Comment by Ravindrakumara** [comment]
Try this is  
npm i --save @fortawesome/fontawesome-svg-core  @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome

**Comment by hilminomad** [comment]
> Try this is
> npm i --save @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome
this one was very useful for the case

**Comment by Damemo** [comment]
> Faced with similar issue, for me helped to install @fortawesome/fontawesome-svg-core

Thanks, helped me resolve same issues in multiple files at once due to this.

**Comment by mikroulie** [comment]
i face this issue:     ./src/components/Navbar.js
Module not found: Can't resolve '@fortawesome/react-fortawesome' in 'C:\Users\Administrator\portfolio\src\components' 
could somebody help?

**Comment by Bangali-Babu** [comment]
After installing forntawsome globally by Command Prompt you have to install in your current working project singly.then it will work

**Comment by jmartincc** [comment]
Just wanted to say this worked for me, using Yarn, and it totally solved the issue. Thanks guys!

**Comment by aliasr2001** [comment]
> Try this is npm i --save @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome

This Really Helped. Thanks Man 😄

**Comment by Ricardo-Javier** [comment]
> 

Thank you!

**Comment by oracularzebra** [comment]
> Try this is npm i --save @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome

Thanks a lot I was searching on the web for 2 hours and yours just solved the problem.

**Comment by Global-Manu-Man** [comment]
excellent solution on problem

**Comment by matheuscaet** [comment]
My case was when I was using the version 6.0.0. I fixed change the version to a valid tag version here: 
https://www.npmjs.com/package/@fortawesome/fontawesome-svg-core
In my case was 6.2.0

**Comment by coffeecode27** [comment]
> Try this is npm i --save @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome

dude you saved my life

**Comment by OrigamiTobichi** [comment]
> Try this is npm i --save @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome

Tks so much , you helped handle issue

**Comment by ambasth05aruni** [comment]
Hey I am facing the same issue.
![Screenshot 2023-03-25 121928](https://user-images.githubusercontent.com/101694582/227701824-8f77cb65-c55c-49aa-9ba7-c034c07a6b09.png)

**Comment by Kimiaghasemian** [comment]
Module not found: Error: Can't resolve '@fortawsome/react-fontawsome' in 'C:\Users\User\Desktop\onlineshop\shop\src\components'
i have this problem and i didnt fixed with npm i ........
could you help me pls?

**Comment by ibams247** [comment]
Module not found: Error: Can't resolve '@fortawesome/free-brands-svg-icons' in 'C:\Users\amma\randoms-qoutes-mach\src\components'
despite trying all the above npm commands I still get the above errors. kindly help

**Comment by robmadole** [comment]
@ambasth05aruni @Kimiaghasemian @ibams247 can you share your `package.json` files? Also, are you all using Vercel?

**Comment by ibams247** [comment]
@robmadole i was able to resolve by re-creating the whole project. but the issue now is that I'm not able to install git in the project . I'm getting this error(npm ERR! A complete log of this run can be found in: C:\Users\amma\AppData\Local\npm-cache\_logs\2024-02-17T04_35_10_377Z-debug-0.log)
